// src/vue/pages/PomoPage.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { readAsyncStorageValue, writeAsyncStorageValue } from '@/core/repository'
import { recordAsyncRepository } from '@/domain/record/repository'
import type { RealityRecord } from '@/domain/record/model'
import { fmtDate } from '@/core/storage'
import { withSaveState } from '@/core/save-state'

type Mode = 'focus' | 'rest'
const defaults: Record<Mode, number> = { focus: 25, rest: 5 }
const prefix = '[番茄钟] 完成专注'
const circumference = 2 * Math.PI * 88
const mode = ref<Mode>('focus'); const minutes = ref({ ...defaults }); const remaining = ref(defaults.focus * 60); const running = ref(false); const stats = ref({ minutes: 0, count: 0 }); const history = ref<RealityRecord[]>([]); const historyLoading = ref(true); const saving = ref(false); const error = ref('')
let timer: number | undefined; let completing = false
const totalSeconds = computed(() => minutes.value[mode.value] * 60)
const progress = computed(() => totalSeconds.value > 0 ? (totalSeconds.value - remaining.value) / totalSeconds.value : 0)
const ringOffset = computed(() => circumference * Math.min(1, Math.max(0, progress.value)))
const recentHistory = computed(() => history.value.slice(0, 8))
const modeLabel = computed(() => mode.value === 'focus' ? '专注' : '休息')
function timeText(seconds: number) { return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}` }
function toast(message: string, kind: 'success' | 'warning' | 'error' = 'success') { window.dispatchEvent(new CustomEvent('beryl-toast', { detail: { message, kind } })) }
async function refreshHistory() { try { historyLoading.value = true; history.value = (await recordAsyncRepository.list()).filter(record => record.body.startsWith(prefix)).sort((a,b) => b.occurredAt-a.occurredAt); error.value = '' } catch(cause) { error.value = cause instanceof Error ? cause.message : '完成记录读取失败' } finally { historyLoading.value = false } }
async function refreshStats() { try { const [total,count] = await Promise.all([readAsyncStorageValue('pomoTotal',0),readAsyncStorageValue('pomoCount',0)]); stats.value = { minutes:Number(total)||0,count:Number(count)||0 } } catch(cause) { error.value = cause instanceof Error ? cause.message : '专注统计读取失败' } }
function retry() { void Promise.all([refreshHistory(),refreshStats()]) }
function clearTimer() { if (timer !== undefined) window.clearInterval(timer); timer = undefined }
async function finishSession() { const completedMode = mode.value; const completedMinutes = minutes.value[completedMode]; if (completedMode === 'focus') { saving.value = true; try { await withSaveState(async () => { const current = await Promise.all([readAsyncStorageValue('pomoTotal',0),readAsyncStorageValue('pomoCount',0)]); const nextMinutes = Number(current[0]) + completedMinutes; const nextCount = Number(current[1]) + 1; if (!await writeAsyncStorageValue('pomoTotal',nextMinutes) || !await writeAsyncStorageValue('pomoCount',nextCount)) throw new Error('专注累计数据保存失败，请检查本地存储状态'); await recordAsyncRepository.create({ type:'fact', body:`${prefix} ${completedMinutes} 分钟`, occurredAt:Date.now(), source:'user' }) }); await refreshStats(); await refreshHistory(); toast(`专注完成，已记录 ${completedMinutes} 分钟`) } catch(cause) { toast(cause instanceof Error ? cause.message : '专注记录保存失败','error') } finally { saving.value = false } } else toast('休息完成，准备开始下一轮专注'); mode.value = 'rest'; remaining.value = minutes.value.rest * 60; completing = false }
function tick() { if (remaining.value <= 1) { remaining.value = 0; running.value = false; clearTimer(); if (!completing) { completing = true; void finishSession() }; return }; remaining.value -= 1 }
function toggleTimer() { if (running.value) { clearTimer(); running.value = false; toast('计时已暂停','warning'); return }; if (remaining.value <= 0) remaining.value = totalSeconds.value; completing = false; running.value = true; document.title = `${timeText(remaining.value)} ${modeLabel.value} — Calmy` }
function resetTimer() { clearTimer(); completing = false; running.value = false; remaining.value = totalSeconds.value }
function changeMode(next: Mode) { clearTimer(); completing = false; running.value = false; mode.value = next; remaining.value = minutes.value[next] * 60 }
function changeMinutes(nextValue: string, selected: Mode) { const next = Math.min(120,Math.max(1,Number(nextValue)||1)); minutes.value = { ...minutes.value,[selected]:next }; if (mode.value === selected && !running.value) remaining.value = next * 60 }
watch([running,remaining,mode], () => { document.title = running.value ? `${timeText(remaining.value)} ${modeLabel.value} — Calmy` : 'Calmy — 专注' })
const onSync = () => { void refreshStats(); void refreshHistory() }
onMounted(() => { void Promise.all([refreshHistory(),refreshStats()]); window.addEventListener('beryl-data-synced',onSync) })
onUnmounted(() => { clearTimer(); window.removeEventListener('beryl-data-synced',onSync); document.title = 'Calmy — 个人现实行动系统' })
watch(running, value => { clearTimer(); if (value) timer = window.setInterval(tick,1000) })
</script>
<template>
  <div class="pomo-page"><header class="page-head"><div><p class="eyebrow">POMO · FOCUSED RHYTHM</p><h1 class="font-title">专注</h1><p>用可调整的专注与休息节奏，把一轮时间落成可追溯的完成记录。</p></div><span class="load-pill">已完成 {{stats.count}} 个专注段 · {{stats.minutes}} 分钟（可选记录）</span></header>
    <section class="beryl-card pomo-panel" style="padding:24px;text-align:center"><div style="display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-bottom:24px"><button class="app-button" :class="{primary:mode==='focus'}" type="button" aria-label="切换到专注模式" :aria-pressed="mode==='focus'" @click="changeMode('focus')" :disabled="saving">专注</button><button class="app-button" :class="{primary:mode==='rest'}" type="button" aria-label="切换到休息模式" :aria-pressed="mode==='rest'" @click="changeMode('rest')" :disabled="saving">休息</button></div>
      <div style="position:relative;display:inline-block"><svg viewBox="0 0 200 200" width="min(70vw, 256px)" height="min(70vw, 256px)" role="img" :aria-label="`${modeLabel}剩余 ${timeText(remaining)}`"><circle cx="100" cy="100" r="88" stroke="var(--c-border-soft)" stroke-width="9" fill="none"/><circle cx="100" cy="100" r="88" :stroke="mode==='focus'?'var(--scene)':'var(--c-success)'" stroke-width="9" fill="none" stroke-linecap="round" :stroke-dasharray="circumference" :stroke-dashoffset="ringOffset" transform="rotate(-90 100 100)"/></svg><div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center"><span class="eyebrow" :style="{color:mode==='focus'?'var(--scene)':'var(--c-success)'}">{{modeLabel}}</span><strong class="font-title" style="font-size:clamp(2.25rem, 8vw, 3.25rem);line-height:1.1">{{timeText(remaining)}}</strong><span class="muted">{{running?'进行中':remaining===totalSeconds?'准备开始':'已暂停'}}</span></div></div>
      <div style="display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:20px"><button class="app-button primary" type="button" :aria-label="running?'暂停专注':'开始专注'" @click="toggleTimer" :disabled="saving">{{running?'暂停':remaining===totalSeconds?'开始':'继续'}}</button><button class="app-button" type="button" aria-label="重置专注" @click="resetTimer" :disabled="saving">重置</button></div>
      <div class="create-row" style="max-width:520px;margin:22px auto 0;grid-template-columns:1fr 1fr"><label class="pomo-duration" style="display:grid;gap:6px;text-align:left;font-size:11px;color:var(--c-text-2)">专注分钟<input aria-label="专注分钟" type="number" min="1" max="120" :value="minutes.focus" @input="changeMinutes(($event.target as HTMLInputElement).value,'focus')" :disabled="running||saving"></label><label class="pomo-duration" style="display:grid;gap:6px;text-align:left;font-size:11px;color:var(--c-text-2)">休息分钟<input aria-label="休息分钟" type="number" min="1" max="120" :value="minutes.rest" @input="changeMinutes(($event.target as HTMLInputElement).value,'rest')" :disabled="running||saving"></label></div>
      <div class="stat-line" style="display:flex;justify-content:center;gap:24px;flex-wrap:wrap;margin-top:20px;color:var(--c-text-2);font-size:12px"><span>专注段 <b style="color:var(--amber)">{{stats.count}}</b> 个</span><span>时间记录 <b style="color:var(--amber)">{{stats.minutes}}</b> 分钟（可选）</span></div></section>
    <section class="beryl-card history-list" aria-labelledby="pomo-history-title" style="padding:18px"><div class="section-title"><div><p class="eyebrow">COMPLETION LOG</p><h2 id="pomo-history-title" class="font-title">完成记录</h2></div><span class="muted">最近 {{recentHistory.length}} 条</span></div><section v-if="error" class="beryl-card empty-state" role="alert" style="margin-top:12px"><b>专注数据暂时无法读取</b><p>{{error}}</p><button class="app-button" type="button" @click="retry">重试</button></section><div v-if="historyLoading" class="empty-state" role="status">正在读取完成记录…</div><div v-else-if="recentHistory.length" aria-live="polite"><article v-for="record in recentHistory" :key="record.calmyId" class="history-card"><p>{{record.body}}</p><small>{{fmtDate(record.occurredAt)}} · 已保存到记录库</small></article></div><div v-else class="empty-state">完成一轮专注后，历史记录会显示在这里。</div></section>
  </div>
</template>

// src/react/pages/PomoPage.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { readAsyncStorageValue, writeAsyncStorageValue } from '@/core/repository'
import { recordAsyncRepository } from '@/domain/record/repository'
import type { RealityRecord } from '@/domain/record/model'
import { fmtDate } from '@/core/storage'
import { withSaveState } from '@/core/save-state'

type PomoMode = 'focus' | 'rest'

const DEFAULT_MINUTES: Record<PomoMode, number> = { focus: 25, rest: 5 }
const POMO_RECORD_PREFIX = '[番茄钟] 完成专注'
const RING_CIRCUMFERENCE = 2 * Math.PI * 88

const toast = (message: string, kind: 'success' | 'warning' | 'error' = 'success') => {
  window.dispatchEvent(new CustomEvent('beryl-toast', { detail: { message, kind } }))
}

interface PomoStats {
  minutes: number
  count: number
}

async function readStats(): Promise<PomoStats> {
  const [minutes, count] = await Promise.all([
    readAsyncStorageValue('pomoTotal', 0),
    readAsyncStorageValue('pomoCount', 0),
  ])
  return {
    minutes: Number(minutes) || 0,
    count: Number(count) || 0,
  }
}

function readHistory(records: RealityRecord[]): RealityRecord[] {
  return records
    .filter(record => record.body.startsWith(POMO_RECORD_PREFIX))
    .sort((a, b) => b.occurredAt - a.occurredAt)
}

function timeText(seconds: number): string {
  return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
}

function modeLabel(mode: PomoMode): string {
  return mode === 'focus' ? '专注' : '休息'
}

export function PomoPage() {
  const [mode, setMode] = useState<PomoMode>('focus')
  const [minutes, setMinutes] = useState(DEFAULT_MINUTES)
  const [remainingSeconds, setRemainingSeconds] = useState(DEFAULT_MINUTES.focus * 60)
  const [running, setRunning] = useState(false)
  const [stats, setStats] = useState<PomoStats>({ minutes: 0, count: 0 })
  const [history, setHistory] = useState<RealityRecord[]>([])
  const [historyLoading, setHistoryLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const timerRef = useRef<number | undefined>(undefined)
  const completingRef = useRef(false)

  const totalSeconds = minutes[mode] * 60
  const progress = totalSeconds > 0 ? (totalSeconds - remainingSeconds) / totalSeconds : 0
  const ringOffset = RING_CIRCUMFERENCE * Math.min(1, Math.max(0, progress))

  async function refreshHistory(): Promise<void> {
    try {
      setHistoryLoading(true)
      setHistory(readHistory(await recordAsyncRepository.list()))
      setError('')
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : '完成记录读取失败')
    } finally {
      setHistoryLoading(false)
    }
  }

  async function refreshStats(): Promise<void> {
    try {
      setStats(await readStats())
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : '专注统计读取失败')
    }
  }

  useEffect(() => {
    void Promise.all([refreshHistory(), refreshStats()])
    const onDataSynced = () => {
      void refreshStats()
      void refreshHistory()
    }
    window.addEventListener('beryl-data-synced', onDataSynced)
    return () => window.removeEventListener('beryl-data-synced', onDataSynced)
  }, [])

  useEffect(() => {
    if (!running) return undefined
    timerRef.current = window.setInterval(() => {
      setRemainingSeconds(current => {
        if (current <= 1) {
          if (!completingRef.current) {
            completingRef.current = true
            setRunning(false)
            void finishSession()
          }
          return 0
        }
        return current - 1
      })
    }, 1000)

    return () => {
      if (timerRef.current !== undefined) window.clearInterval(timerRef.current)
      timerRef.current = undefined
    }
  }, [running])

  useEffect(() => {
    document.title = running
      ? `${timeText(remainingSeconds)} ${modeLabel(mode)} — Calmy`
      : 'Calmy — 专注'
    return () => {
      document.title = 'Calmy — 个人现实行动系统'
    }
  }, [mode, remainingSeconds, running])

  async function finishSession(): Promise<void> {
    const completedMode = mode
    const completedMinutes = minutes[completedMode]
    if (completedMode === 'focus') {
      setSaving(true)
      try {
        await withSaveState(async () => {
          const current = await readStats()
          const nextMinutes = current.minutes + completedMinutes
          const nextCount = current.count + 1
          if (!await writeAsyncStorageValue('pomoTotal', nextMinutes) || !await writeAsyncStorageValue('pomoCount', nextCount)) {
            throw new Error('专注累计数据保存失败，请检查本地存储状态')
          }
          await recordAsyncRepository.create({
            type: 'fact',
            body: `${POMO_RECORD_PREFIX} ${completedMinutes} 分钟`,
            occurredAt: Date.now(),
            source: 'user',
          })
        })
        setStats(await readStats())
        await refreshHistory()
        toast(`专注完成，已记录 ${completedMinutes} 分钟`)
      } catch (cause) {
        toast(cause instanceof Error ? cause.message : '专注记录保存失败', 'error')
      } finally {
        setSaving(false)
      }
    } else {
      toast('休息完成，准备开始下一轮专注')
    }

    setMode('rest')
    setRemainingSeconds(minutes.rest * 60)
    completingRef.current = false
  }

  function clearTimer(): void {
    if (timerRef.current !== undefined) window.clearInterval(timerRef.current)
    timerRef.current = undefined
  }

  function toggleTimer(): void {
    if (running) {
      clearTimer()
      setRunning(false)
      toast('计时已暂停', 'warning')
      return
    }
    if (remainingSeconds <= 0) setRemainingSeconds(totalSeconds)
    completingRef.current = false
    setRunning(true)
  }

  function resetTimer(): void {
    clearTimer()
    completingRef.current = false
    setRunning(false)
    setRemainingSeconds(totalSeconds)
  }

  function changeMode(nextMode: PomoMode): void {
    clearTimer()
    completingRef.current = false
    setRunning(false)
    setMode(nextMode)
    setRemainingSeconds(minutes[nextMode] * 60)
  }

  function changeMinutes(nextValue: string): void {
    const nextMinutes = Math.min(120, Math.max(1, Number(nextValue) || 1))
    setMinutes(current => ({ ...current, [mode]: nextMinutes }))
    if (!running) setRemainingSeconds(nextMinutes * 60)
  }

  const recentHistory = useMemo(() => history.slice(0, 8), [history])

  return (
    <div className="pomo-page">
      <header className="page-head">
        <div>
          <p className="eyebrow">POMO · FOCUSED RHYTHM</p>
          <h1 className="font-title">专注</h1>
          <p>用可调整的专注与休息节奏，把一轮时间落成可追溯的完成记录。</p>
        </div>
        <span className="load-pill">已完成 {stats.count} 个专注段 · {stats.minutes} 分钟（可选记录）</span>
      </header>

      <section className="beryl-card" style={{ padding: 24, textAlign: 'center' }}>
        <div style={{ display: 'flex', justifyContent: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 24 }}>
          <button className={`react-btn ${mode === 'focus' ? 'primary' : ''}`} type="button" aria-label="切换到专注模式" aria-pressed={mode === 'focus'} onClick={() => changeMode('focus')} disabled={saving}>专注</button>
          <button className={`react-btn ${mode === 'rest' ? 'primary' : ''}`} type="button" aria-label="切换到休息模式" aria-pressed={mode === 'rest'} onClick={() => changeMode('rest')} disabled={saving}>休息</button>
        </div>

        <div style={{ position: 'relative', display: 'inline-block' }}>
          <svg viewBox="0 0 200 200" width="min(70vw, 256px)" height="min(70vw, 256px)" role="img" aria-label={`${modeLabel(mode)}剩余 ${timeText(remainingSeconds)}`}>
            <circle cx="100" cy="100" r="88" stroke="var(--c-border-soft)" strokeWidth="9" fill="none" />
            <circle
              cx="100"
              cy="100"
              r="88"
              stroke={mode === 'focus' ? 'var(--scene)' : 'var(--c-success)'}
              strokeWidth="9"
              fill="none"
              strokeLinecap="round"
              strokeDasharray={RING_CIRCUMFERENCE}
              strokeDashoffset={ringOffset}
              transform="rotate(-90 100 100)"
            />
          </svg>
          <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
            <span className="eyebrow" style={{ color: mode === 'focus' ? 'var(--scene)' : 'var(--c-success)' }}>{modeLabel(mode)}</span>
            <strong className="font-title" style={{ fontSize: 'clamp(2.25rem, 8vw, 3.25rem)', lineHeight: 1.1 }}>{timeText(remainingSeconds)}</strong>
            <span className="muted">{running ? '进行中' : remainingSeconds === totalSeconds ? '准备开始' : '已暂停'}</span>
          </div>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', gap: 8, flexWrap: 'wrap', marginTop: 20 }}>
          <button className="react-btn primary" type="button" aria-label={running ? '暂停专注' : '开始专注'} onClick={toggleTimer} disabled={saving}>{running ? '暂停' : remainingSeconds === totalSeconds ? '开始' : '继续'}</button>
          <button className="react-btn" type="button" aria-label="重置专注" onClick={resetTimer} disabled={saving}>重置</button>
        </div>

        <div className="create-row" style={{ maxWidth: 520, margin: '22px auto 0', gridTemplateColumns: '1fr 1fr' }}>
          <label style={{ display: 'grid', gap: 6, textAlign: 'left', fontSize: 11, color: 'var(--c-text-2)' }}>
            专注分钟
            <input type="number" min="1" max="120" value={minutes.focus} onChange={event => { if (mode === 'focus') changeMinutes(event.target.value); else setMinutes(current => ({ ...current, focus: Math.min(120, Math.max(1, Number(event.target.value) || 1)) })) }} disabled={running || saving} />
          </label>
          <label style={{ display: 'grid', gap: 6, textAlign: 'left', fontSize: 11, color: 'var(--c-text-2)' }}>
            休息分钟
            <input type="number" min="1" max="120" value={minutes.rest} onChange={event => { if (mode === 'rest') changeMinutes(event.target.value); else setMinutes(current => ({ ...current, rest: Math.min(120, Math.max(1, Number(event.target.value) || 1)) })) }} disabled={running || saving} />
          </label>
        </div>

        <div className="stat-line" style={{ display: 'flex', justifyContent: 'center', gap: 24, flexWrap: 'wrap', marginTop: 20, color: 'var(--c-text-2)', fontSize: 12 }}>
          <span>专注段 <b style={{ color: 'var(--amber)' }}>{stats.count}</b> 个</span>
          <span>时间记录 <b style={{ color: 'var(--amber)' }}>{stats.minutes}</b> 分钟（可选）</span>
        </div>
      </section>

      <section className="beryl-card history-list" aria-labelledby="pomo-history-title" style={{ padding: 18 }}>
        <div className="section-title">
          <div>
            <p className="eyebrow">COMPLETION LOG</p>
            <h2 id="pomo-history-title" className="font-title">完成记录</h2>
          </div>
          <span className="muted">最近 {recentHistory.length} 条</span>
        </div>
        {error && <section className="beryl-card empty-state" role="alert" style={{ marginTop: 12 }}><b>专注数据暂时无法读取</b><p>{error}</p><button className="react-btn" type="button" onClick={() => void Promise.all([refreshHistory(), refreshStats()])}>重试</button></section>}
        {historyLoading ? <div className="empty-state" role="status">正在读取完成记录…</div> : recentHistory.length ? (
          <div aria-live="polite">
            {recentHistory.map(record => (
              <article className="history-card" key={record.calmyId}>
                <p>{record.body}</p>
                <small>{fmtDate(record.occurredAt)} · 已保存到记录库</small>
              </article>
            ))}
          </div>
        ) : (
          <div className="empty-state">完成一轮专注后，历史记录会显示在这里。</div>
        )}
      </section>
    </div>
  )
}
